### ISSUE TITLE
meta:description improvements

### ISSUE THREAD

**Issue by RMHogervorst** [RMHogervorst/blog#41]
All posts have rich html metadata that I created with hugo. 

What works great is title, author etc. 

- [ ] the meta description in both twitter: description and og:description is the subtitle now. that is not great. I might have to add an extra field in the yaml frontmatter and only fall back on subtitle when none is given. 
- [ ] twitter:site links to my profile, which is not great
- [ ] og:type is now website, could be article, linkedin sees type=article

## metavalidator
title too long?
description is short (it's the subtitle)
them color?, 
keywords not set
robots not set

## Google structured data result
- author (missing field url, optional, type=thing, name=valid)
- description is great

## Open graph tags analyzer
- og:type should be article for blog pages, and website for the rest
- og:locale content "en_US"

article:published_time
article:modified_time datetime
article:tag should be tags(stringarray)
article:author: 
- profile:first_name string
- profile:last_name string
- profile:username: string

## Linkedin
- [ ] linkedin cannot find a published date
- [ ] description is to little words (should be 100 characters)

### Schema.org
schema.org has all the right information: date published, date modified, image, keywords, it even has wordcount
author is @type thing? not human?, name is correct. 

<https://www.clairecodes.com/blog/2019-05-03-meta-descriptions-in-hugo-templates/>

**Comment by RMHogervorst** [comment]
Adding a description yaml adds the correct description to twitter. 
Correct for twitter
Linkedin still not correct, type =article works. publish date not.
linkedin uses og:description, but that one is still wrong?

**Comment by RMHogervorst** [comment]
metavalidator: description is a bit too long. 
keywords not working

twitter site is missing. 

opengraph
- description works, 
- og:type article works. 

linkedin checker
- type article correct.
- description is still wrong, uses name=desscription property og:description but shows subtitle (odd, because it also looks at alternate values
- cannot find published date

**Comment by RMHogervorst** [comment]
property="og:article:author" ?



Add this to rmhogervorst.nl
```
<meta property="og:type" content="profile">
<meta property="profile:first_name" content="Roel M.">
<meta property="profile:last_name" content="Hogervorst">
<meta property="profile:username" content="rmhogervorst"> 
```

**Comment by RMHogervorst** [comment]
superweird

So I have this
`<meta name=article-published_time property="og:article:published_time" content="2022-10-25T00:00:00+00:00">`
NOS story has a functional datetime in sharing and has
`<meta content="2022-10-24T12:26:37+0200" property="og:article:published_time"/>`

Does it pick up something else?
It has a <time datetime=""> content </time>

I have `<time class=dt-published datetime="2022-10-25 00:00:00 +0000 UTC">Posted on October 25, 2022</time>`
they have 
`<time dateTime="2022-10-24T12:26:37+0200">vandaag, 12:26</time>`
so it might be the datetime formatting?

Changed to `<time class=dt-published datetime=2022-10-25T00:00:00+00:00>Posted on October 25, 2022</time>` sthill not working

**Comment by RMHogervorst** [comment]
fuck, it might be the `dateTime`?

**Comment by RMHogervorst** [comment]
`<meta name=article-published_time property="og:article:published_time" content="2022-10-25T00:00:00+00:00">`

**Comment by RMHogervorst** [comment]
alright, I don't know how NOS does it, but I can't get it to work
